global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'eureka-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8761' ]  # Eureka Server의 메트릭 엔드포인트

  - job_name: 'gateway-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8050' ]  # Gateway 서비스의 메트릭 엔드포인트

  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:0' ]  # User 서비스의 메트릭 엔드포인트

  - job_name: 'concert-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:0' ]  # Concert 서비스의 메트릭 엔드포인트

  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:0' ]  # Order 서비스의 메트릭 엔드포인트

