server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: api-gateway
  config:
    import: "configserver:"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # User Service Route
        - id: user-service-public
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/signup, /api/v1/users/login
        - id: user-service-private
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AuthenticationFilter
        - id: user-service-openapi
          uri: lb://user-service
          predicates:
            - Path=/v3/api-docs/user-service
          filters:
            - RewritePath=/v3/api-docs/user-service,/v3/api-docs
        # Game Service Routes
        - id: game-service
          uri: lb://game-service
          predicates:
            - Path=/api/v1/games/** ,/api/v2/games/**
          filters:
            - AuthenticationFilter
        - id: game-service-openapi
          uri: lb://game-service
          predicates:
            - Path=/v3/api-docs/game-service
          filters:
            - RewritePath=/v3/api-docs/game-service,/v3/api-docs
        # Point Service Routes
        - id: point-service
          uri: lb://point-service
          predicates:
            - Path=/api/v1/points/**
          filters:
            - AuthenticationFilter
        - id: point-service-openapi
          uri: lb://point-service
          predicates:
            - Path=/v3/api-docs/point-service
          filters:
            - RewritePath=/v3/api-docs/point-service,/v3/api-docs
        # Betting Service Routes
        - id: betting-service
          uri: lb://betting-service-blue
          predicates:
            - Path=/api/v1/bets/**
          filters:
            - AuthenticationFilter
        - id: betting-service-openapi
          uri: lb://betting-service-blue
          predicates:
            - Path=/v3/api-docs/betting-service
          filters:
            # /v3/api-docs/betting-service -> /v3/api-docs
            - RewritePath=/v3/api-docs/betting-service,/v3/api-docs
  data:
    redis:
      host: redis      # docker-compose 서비스 이름
      port: 6379

springdoc:
  api-docs:
    enabled: true
  enable-spring-security: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: betting-service
        url: /v3/api-docs/betting-service
      - name: game-service
        url: /v3/api-docs/game-service
      - name: point-service
        url: /v3/api-docs/point-service
      - name: user-service
        url: /v3/api-docs/user-service

management:
  endpoints:
    web:
      exposure:
        include: refresh