jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  token:
    expiration: 900000
  refresh:
    expiration: 1209600000

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info, prometheus
  metrics:
    tags:
      application: ${spring.application.name}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

slack:
  web-hook-url: ${SLACK_WEBHOOK_URL}