jwt:
  secret:
    key: ${JWT_SECRET_KEY}
  token:
    expiration: 900000
  refresh:
    expiration: 1209600000

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info, prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

slack:
  web-hook-url: ${SLACK_WEBHOOK_URL}


