server:
  port: 0

spring:
  application:
    name: game-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    # DB 연결 지연 활성화
    initialization-mode: always
    continue-on-error: true
    # DataSource 초기화 지연 설정
    # DB 컨테이너가 준비될 때까지 애플리케이션 시작을 지연시킵니다.
    hikari:
      maximum-pool-size: 10
      # 연결이 성공할 때까지 무한히 재시도
      initialization-fail-timeout: -1

  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: game-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

    properties:
      spring.json.trusted.packages: "*"

    topics:
      game-completed: gameResult

  jpa:
    # 1. JPA Database Type 명시
    database: postgresql
    # 2. JPA Database Platform 명시 (Hibernate Dialect의 최신 표준)
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: games
  cloud:
    service-bindings:
      # DB 연결이 준비 상태(up)가 될 때까지 기다립니다.
      enabled: true

management:
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0