CREATE SCHEMA IF NOT EXISTS users   AUTHORIZATION oneonone;
CREATE SCHEMA IF NOT EXISTS games   AUTHORIZATION oneonone;
CREATE SCHEMA IF NOT EXISTS bets    AUTHORIZATION oneonone;
CREATE SCHEMA IF NOT EXISTS points  AUTHORIZATION oneonone;
CREATE SCHEMA IF NOT EXISTS outboxes AUTHORIZATION oneonone;