name: Game Service Deploy

on:
  push:
    paths:
      - game-service/**
    branches: [ main, dev, release ]

jobs:
  deploy:
    uses: ./.github/workflows/deploy-template.yml
    with:
      service: game-service